[build]
  base      = "frontend"
  command   = "npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION = "20.17.0"
  NPM_VERSION  = "10.5.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

